# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cstatus.proto\"\xd7\x02\n\tCpuStatus\x12\r\n\x05\x63ores\x18\x01 \x02(\x05\x12\x10\n\x08\x63puTotal\x18\x02 \x02(\x02\x12\r\n\x05\x63ore0\x18\x03 \x02(\x02\x12\r\n\x05\x63ore1\x18\x04 \x02(\x02\x12\r\n\x05\x63ore2\x18\x05 \x02(\x02\x12\r\n\x05\x63ore3\x18\x06 \x02(\x02\x12\r\n\x05\x63ore4\x18\x07 \x02(\x02\x12\r\n\x05\x63ore5\x18\x08 \x02(\x02\x12\r\n\x05\x63ore6\x18\t \x02(\x02\x12\r\n\x05\x63ore7\x18\n \x02(\x02\x12\r\n\x05\x63ore8\x18\x0b \x02(\x02\x12\r\n\x05\x63ore9\x18\x0c \x02(\x02\x12\x0e\n\x06\x63ore10\x18\r \x02(\x02\x12\x0e\n\x06\x63ore11\x18\x0e \x02(\x02\x12\x13\n\x0bmem_percent\x18\x0f \x02(\x02\x12\x11\n\tmem_total\x18\x10 \x02(\x02\x12\x15\n\rmem_available\x18\x11 \x02(\x02\x12\x14\n\x0c\x64isk_percent\x18\x12 \x02(\x02\x12\x0e\n\x06net_up\x18\x13 \x02(\x02\x12\x0e\n\x06net_dw\x18\x14 \x02(\x02'
)




_CPUSTATUS = _descriptor.Descriptor(
  name='CpuStatus',
  full_name='CpuStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cores', full_name='CpuStatus.cores', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpuTotal', full_name='CpuStatus.cpuTotal', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core0', full_name='CpuStatus.core0', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core1', full_name='CpuStatus.core1', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core2', full_name='CpuStatus.core2', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core3', full_name='CpuStatus.core3', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core4', full_name='CpuStatus.core4', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core5', full_name='CpuStatus.core5', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core6', full_name='CpuStatus.core6', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core7', full_name='CpuStatus.core7', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core8', full_name='CpuStatus.core8', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core9', full_name='CpuStatus.core9', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core10', full_name='CpuStatus.core10', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core11', full_name='CpuStatus.core11', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_percent', full_name='CpuStatus.mem_percent', index=14,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_total', full_name='CpuStatus.mem_total', index=15,
      number=16, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mem_available', full_name='CpuStatus.mem_available', index=16,
      number=17, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disk_percent', full_name='CpuStatus.disk_percent', index=17,
      number=18, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_up', full_name='CpuStatus.net_up', index=18,
      number=19, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_dw', full_name='CpuStatus.net_dw', index=19,
      number=20, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=360,
)

DESCRIPTOR.message_types_by_name['CpuStatus'] = _CPUSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CpuStatus = _reflection.GeneratedProtocolMessageType('CpuStatus', (_message.Message,), {
  'DESCRIPTOR' : _CPUSTATUS,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:CpuStatus)
  })
_sym_db.RegisterMessage(CpuStatus)


# @@protoc_insertion_point(module_scope)
